language: java
jdk:
  - openjdk14

# создание БД для тестов
services:
  - postgresql
before_install:
  - psql -c "CREATE DATABASE forum;" -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

install: true

script: mvn clean package -DskipTests=true

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на selesitomorozov@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - selesitomorozov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="3a37acdb-bfcf-404c-b33b-266ca71c3de7"

deploy:
  provider: heroku
  api_key:
    secure: jqC52llgcghiK3mgXBiLsQWgK4xInf62RwnRjXddRAHnb8QB4utpmY27JOiegQ0LVfXZYsd8TQ7M8tqQp5JWRxeXpVRRe8+gybsDZ3xvbls8/CRKsVP/IWkufG3dXBRyO6TyfQqwDxy2pjfrU0HRj7yB+IPpmzZCdzyUWQvmY8TT4OtR7VfG1OWEK1p25dRJub55zdJ5jqc2/HW/GEv2m8lplO08lS72eUNH6ZtdlEr0aiaVQyjtS0wHOCwhMaRTbZwwpfguX2jxY42dmfxmpRj557Xh1Kf0/lYrUPRbjG1e2VwJz9/kQOv8gttorxH8yv2J9dagp/eCVR7WEWrHZDVn37PgtmMx/FXoZWLKrzSmb0tNiGDjK6lgiiGbz6r4C/ktutCCLiKTsFrlSqnG03ZcgeK1I7zoh7u8vDHzyXauYhvpXz+h7IP67kc9cMt2s6Ybf+o7I8ezrVxm8fvACr328qUZjkGTjiTpI+RLe/JQPg0t3O4dMxbJ0t2umYSqnkK/EhQoeoNLnwLpMjTHzXJ6xCyFM17u8i6Hw5wXPkgoHLT5bm+9Fdbviu+oYF1HZ/xSL1PqAM6E9SIJKBRTZyyXu84wWLs/zAnuJRK9pMR5MeaMFimFa50OzxQH75FtbmoiQRnyQNbipsbcccKajikYx38KPU2sz64dbyAlRWQ=
  app: immense-ravine-02598

